### ISSUE TITLE
Log messages from iterwalk are unhelpful in the gui

### ISSUE THREAD

**Issue by ZLLentz** [slaclab/pswalker#57]
Since the log messages display the pre-rotation-correction x positions, these are confusing at the top level in the gui, which has all numbers rotation-corrected. I'm not sure what the best way to solve this is.

**Comment by teddyrendahl** [comment]
Maybe just change the log message to display the error as opposed to absolute position?

**Comment by ZLLentz** [comment]
I like that idea
